import { GeistSans } from "geist/font/sans";
import { GeistMono } from 'geist/font/mono'
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${GeistSans.variable} ${GeistMono.variable}`}>
      <body>
        <div id="root" className="px-6 pt-32 text-slate-600 bg-gray-100 min-h-screen">
          {children}
        </div>
      </body>
    </html>
  );
}
